services:
  - type: web
    name: prousta
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn prousta.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://prousta.az,https://www.prousta.az"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
