# Generated by Django 6.0.3 on 2026-03-23 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bashliq', models.CharField(max_length=200)),
                ('acaqlama', models.TextField()),
                ('qiymet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('veziyyet', models.CharField(choices=[('yeni', 'Yeni'), ('ishlenmish', 'İşlənmiş')], default='yeni', max_length=20)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('gozlemede', 'Gözləmədə'), ('deaktiv', 'Deaktiv')], default='gozlemede', max_length=20)),
                ('sheher', models.CharField(default='Bakı', max_length=100)),
                ('baxish_sayi', models.PositiveIntegerField(default=0)),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('yenilendi', models.DateTimeField(auto_now=True)),
                ('istifadeci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elanlar', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
            ],
            options={
                'verbose_name_plural': 'Elanlar',
                'ordering': ['-yaradildi'],
            },
        ),
        migrations.CreateModel(
            name='ElanShekil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shekil', models.ImageField(upload_to='elanlar/')),
                ('əsas', models.BooleanField(default=False)),
                ('elan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shekillar', to='core.elan')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('sheher', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatarlar/')),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('istifadeci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('elan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritler', to='core.elan')),
                ('istifadeci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('istifadeci', 'elan')},
            },
        ),
    ]
