# Generated by Django 6.0.3 on 2026-03-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElanTelefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomre', models.CharField(max_length=20)),
                ('elan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telefon', to='core.elan')),
            ],
        ),
    ]
