# Generated by Django 5.2.1 on 2026-03-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_elantelefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elan',
            options={'ordering': ['-vip_status', '-yaradildi'], 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.RenameField(
            model_name='elanshekil',
            old_name='əsas',
            new_name='esas',
        ),
        migrations.RemoveField(
            model_name='elan',
            name='veziyyet',
        ),
        migrations.AddField(
            model_name='elan',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='elan',
            name='vip_bitis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='vip_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('super_vip', 'Super VIP')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='kategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kateqoriyalar', to='core.kategori'),
        ),
        migrations.AddField(
            model_name='profil',
            name='balans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn', models.TextField()),
                ('oxundu', models.BooleanField(default=False)),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('elan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='core.elan')),
                ('gonderici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['yaradildi'],
            },
        ),
        migrations.CreateModel(
            name='Odenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nov', models.CharField(choices=[('vip', 'VIP Elan'), ('super_vip', 'Super VIP Elan'), ('balans', 'Balans Artırma')], max_length=20)),
                ('mebleg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('gozlemede', 'Gözləmədə'), ('tesdiq_edildi', 'Təsdiq edildi'), ('legv_edildi', 'Ləğv edildi')], default='gozlemede', max_length=20)),
                ('qebz', models.ImageField(blank=True, null=True, upload_to='qebzler/')),
                ('qeyd', models.TextField(blank=True)),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('elan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.elan')),
                ('istifadeci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odenisler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ödənişlər',
            },
        ),
        migrations.DeleteModel(
            name='ElanTelefon',
        ),
    ]
