# Generated by Django 5.2.1 on 2026-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_elan_options_rename_əsas_elanshekil_esas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elan',
            options={'ordering': ['-yaradildi'], 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.AlterField(
            model_name='elan',
            name='vip_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP — 10 gün'), ('super_vip', 'Super VIP — 30 gün')], default='normal', max_length=20),
        ),
    ]
