# Generated by Django 5.2.1 on 2026-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_elan_options_alter_elan_vip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='bitis_tarixi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='nomre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='elan',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('gozlemede', 'Gözləmədə'), ('deaktiv', 'Deaktiv'), ('muddeti_bitmis', 'Müddəti Bitmiş')], default='gozlemede', max_length=20),
        ),
    ]
