# Generated by Django 5.2.1 on 2026-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_elan_bitis_tarixi_elan_nomre_alter_elan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='nomre',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
