# Generated by Django 5.2.1 on 2026-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_elan_nomre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='soyad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
