# Generated by Django 5.2.1 on 2026-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profil_ad_profil_soyad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elan',
            options={'ordering': ['-vip_status', '-yaradildi'], 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.AlterField(
            model_name='elan',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('gozlemede', 'Gözləmədə'), ('deaktiv', 'Deaktiv'), ('muddeti_bitmis', 'Müddəti Bitmiş')], db_index=True, default='gozlemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='elan',
            name='vip_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP — 10 gün'), ('super_vip', 'Super VIP — 30 gün')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='oxundu',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
