# Generated by Django 5.2.1 on 2026-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMelumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_adi', models.CharField(default='ABB Bank', max_length=100)),
                ('kart_nomresi', models.CharField(blank=True, max_length=50)),
                ('kart_sahibi', models.CharField(default='Prousta MMC', max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank Məlumatı',
                'verbose_name_plural': 'Bank Məlumatları',
            },
        ),
    ]
