# Generated by Django 5.2.1 on 2026-04-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_bank_melumat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elan',
            options={'ordering': ['-vip_siralama', '-yaradildi'], 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.AddField(
            model_name='elan',
            name='vip_siralama',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kateqoriyalar', to='core.kategori'),
        ),
    ]
