# Generated by Django 5.2.1 on 2026-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_elan_vip_yenilendi_alter_problem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movqe', models.CharField(choices=[('sol', 'Sol Yan Banner (Desktop)'), ('sag', 'Sağ Yan Banner (Desktop)'), ('orta', 'Orta / Horizontal Banner')], max_length=20, unique=True, verbose_name='Mövqe')),
                ('bashliq', models.CharField(blank=True, max_length=150, verbose_name='Başlıq / Müştəri adı')),
                ('link', models.URLField(blank=True, help_text='Məsələn: https://example.com və ya https://wa.me/99450xxxxxxx', verbose_name='Keçid Linki (URL)')),
                ('shekil', models.ImageField(blank=True, help_text='Yan bannerlər üçün tövsiyə olunan ölçü: 160x600 və ya 120x600', null=True, upload_to='bannerler/', verbose_name='Banner Şəkli')),
                ('html_kod', models.TextField(blank=True, help_text='Google AdSense və ya xüsusi script kodu', verbose_name='HTML / AdSense Kodu (Şəkil yoxdursa)')),
                ('aktiv', models.BooleanField(db_index=True, default=True, verbose_name='Aktivdir')),
                ('bitis_tarixi', models.DateTimeField(blank=True, help_text='Boş buraxsanız müddətsiz aktiv olar', null=True, verbose_name='Bitmə tarixi')),
                ('yaradildi', models.DateTimeField(auto_now_add=True)),
                ('yenilendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklam Banneri',
                'verbose_name_plural': 'Reklam Bannerləri',
            },
        ),
    ]
