# Generated by Django 5.2.1 on 2026-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reklambanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklambanner',
            name='movqe',
            field=models.CharField(choices=[('ust', 'Üst Banner (Tam Enli - Ekran Boyu)'), ('sol', 'Sol Yan Banner (Desktop)'), ('sag', 'Sağ Yan Banner (Desktop)'), ('orta', 'Orta / Horizontal Banner')], max_length=20, unique=True, verbose_name='Mövqe'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='shekil',
            field=models.ImageField(blank=True, help_text='Üst banner üçün tövsiyə olunan ölçü: 1920x150 və ya 1200x120. Yan bannerlər üçün: 160x600 və ya 120x600', null=True, upload_to='bannerler/', verbose_name='Banner Şəkli'),
        ),
    ]
