# Generated by Django 5.2.1 on 2026-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_reklambanner_movqe_alter_reklambanner_shekil'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklambanner',
            name='animasiya_effekti',
            field=models.CharField(choices=[('none', 'Standart (Statik / Normal)'), ('zoom', 'Zərif Yaxınlaşma (Smooth Zoom on Hover)'), ('glow', 'İşıqlı Parıltı (Glow / Parlaq animasiya)'), ('pulse', 'Nəbzlənmə (Pulse animasiya)')], default='zoom', max_length=20, verbose_name='Animasiya Effekti'),
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='video',
            field=models.FileField(blank=True, help_text='Animasiyalı video banner üçün MP4 və ya WebM faylı (avtomatik və səssiz oxunur)', null=True, upload_to='bannerler/videolar/', verbose_name='Video Faylı (MP4 / WebM)'),
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='video_url',
            field=models.URLField(blank=True, help_text='Cloudinary və ya digər birbaşa video linki', verbose_name='Video Linki (Birbaşa MP4 / WebM URL)'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='html_kod',
            field=models.TextField(blank=True, help_text='HTML5 Canvas, CSS animasiya, Lottie, SVG və ya script kodu', verbose_name='HTML / Animasiya / AdSense Kodu'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='shekil',
            field=models.ImageField(blank=True, help_text='Şəkil və ya GIF animasiya (1920x150, 160x600 və s.)', null=True, upload_to='bannerler/', verbose_name='Banner Şəkli / GIF'),
        ),
    ]
