# Generated by Django 5.2.1 on 2026-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reklambanner_animasiya_effekti_reklambanner_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklambanner',
            name='bos_olduqda_gizlet',
            field=models.BooleanField(default=False, help_text='İşarələnsə, bu mövqedə aktiv reklam (şəkil/video) olmadıqda banner saytda heç bir yer tutmayacaq və tam gizlənəcək', verbose_name='Reklam yoxdursa banneri gizlət'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='shekil',
            field=models.ImageField(blank=True, help_text='Şəkil və ya GIF animasiya (Üst: 1920x400, Yan: 160x600 və s.)', null=True, upload_to='bannerler/', verbose_name='Banner Şəkli / GIF'),
        ),
    ]
